#!/bin/bash

# Sends a simple trap to localhost
#
# This is a helper script to debug the Python package "puresnmp". It was
# written to have a usable example of "snmptrap" at hand in the repository.
#
# Quick reference
#   - First positional argument is the host to which the Trap is sent to
#   - Second positional argument is the uptime of the host. If empty a sensible
#     default value is chosen by "snmptrap"
#   - The third positional argument is the trap identifier
#   - The following positional arguments are triples with the items
#       - OID
#       - data-type
#       - value
#   See the "snmptrap" manpage for details


snmptrap \
    -v2c \
    -c public \
    localhost \
    '' \
    1.3.6.1.4.1.8072.2.3.0.1 \
    1.3.6.1.4.1.8072.2.3.2.1 i 123456 \
    1.3.6.1.4.1.8072.2.3.2.2 s hello-world
